#!/bin/bash

SELFDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
CONFIGDIR=$SELFDIR/config

HOMECONFIGDIR=~/.config
mkdir -p $HOMECONFIGDIR

CONFIGCONTENT=`ls $CONFIGDIR`

for CONTENT in $CONFIGCONTENT
do
    ln -s "$CONFIGDIR/$CONTENT" $HOMECONFIGDIR
done
